# Script to only plot certain branches of the GAGA phylogenetic tree i.e. Formicinae subfamily 

```{r}
require(ggplot2)
require(ape)
require(ggtree)
library(treeio)
library(phytools)
library(tidytree)
library(dplyr)
```


# load tree
```{r}
# Whole tree
GAGA.tree<-load("/Users/Janina/sciebo/MASTER/Masterarbeit/lgt/0_data/GAGA.tree.plot4.Robject")
GAGA.tree.plot4+geom_tippoint(aes(col=Subfamily))


# To plot only subfamilies or selected species
GAGA2.tree<-read.tree("/Users/Janina/sciebo/MASTER/Masterarbeit/lgt/0_data/GAGA_dated_phylogeny_newick_woutgroup_DatesPeters2017_CurrBio.tre")


# load id2species table
GAGA.data<-read.table("/Users/Janina/sciebo/MASTER/Masterarbeit/lgt/0_data/GAGA.data.tsv",sep="\t",T)
GAGA.all.data<-read.table("/Users/Janina/sciebo/MASTER/Masterarbeit/lgt/0_data/all.GAGA.data.tsv",sep="\t",T)
```


# define which ids to extract
```{r}
# Create new tree object and subset to the species you want to keep
Formicinae2 <- GAGA.tree.plot4$data %>%
  filter(Subfamily == "Formicinae")

Myrmicinae <- GAGA.tree.plot4$data %>%
  filter(Subfamily == "Myrmicinae")

# define which ids to extract
Formi.selection<-c("GAGA-0055","GAGA-0406","GAGA-0304","GAGA-0334","GAGA-0494","GAGA-0354","GAGA-0350","GAGA-0359","GAGA-0485","NCBI-0008","GAGA-0495","OUT-0001","OUT-0002","GAGA-0502","GAGA-0200","GAGA-0221","GAGA-0361","GAGA-0362","NCBI-0005","GAGA-0396","GAGA-0374","GAGA-0360","GAGA-0336","GAGA-0187","GAGA-0338","GAGA-0199")

Myrmi.selection<-c("GAGA-0082","GAGA-0103","GAGA-0256","GAGA-0098","GAGA-0099","GAGA-0463",
                   "GAGA-0222","GAGA-0223","GAGA-0512","GAGA-0513","GAGA-0224","GAGA-0511",
                   "GAGA-0288","GAGA-0510","GAGA-0407","GAGA-0165","NCBI-0013","GAGA-0330",
                   "GAGA-0393","GAGA-0395","GAGA-0335","GAGA-0328","GAGA-0382","GAGA-0579",
                   "GAGA-0331","GAGA-0378","GAGA-0578","GAGA-0533","GAGA-0520","GAGA-0333",
                   "GAGA-0553","GAGA-0527","GAGA-0085","GAGA-0405","GAGA-0515")

GAGA.tree.Formicinae<-tidytree::keep.tip(GAGA2.tree,Formi.selection)

GAGA.tree.Myrmicinae<-tidytree::keep.tip(GAGA2.tree,Myrmi.selection)

# add id2species data to tree
GAGA.tree.Formicinae.plot<-ggtree(GAGA.tree.Formicinae,size=.2) %<+% GAGA.data

GAGA.tree.Myrmicinae.plot<-ggtree(GAGA.tree.Myrmicinae,size=.2) %<+% GAGA.data
```


```{r}
# Formicinae: add labels to plot and 
GAGA.tree.Formicinae.plot<-ggtree(GAGA.tree.Formicinae,size=1) %<+% GAGA.data +
  geom_tiplab(aes(label=paste0(label," ",DisplayName)),
              size=2,
              show.legend=F,
              fontface="italic",
              offset=20)+
  geom_rootedge(.005,size=.2)+
  xlim_tree(250)

GAGA.tree.Formicinae.plot

ggsave("/Users/Janina/Documents/MASTER/Masterarbeit/plots/GAGA_phylogenies/selected_Formicinae_only.pdf",width=10,height=15) #save the tree in a pdf

# Myrmicinae: add labels to plot and 
GAGA.tree.Myrmicinae.plot<-ggtree(GAGA.tree.Myrmicinae,size=1) %<+% GAGA.data +
  geom_tiplab(aes(label=paste0(label," ",DisplayName)),
              size=2,
              show.legend=F,
              fontface="italic",
              offset=20)+
  geom_rootedge(.005,size=.2)+
  xlim_tree(250)

GAGA.tree.Myrmicinae.plot

ggsave("/Users/Janina/Documents/MASTER/Masterarbeit/plots/GAGA_phylogenies/selected_Myrmicinae_only.pdf",width=10,height=15) #save the tree in a pdf
```
```


