---
title: "Function_analysis"
author: "Janina Rinke"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
library(knitr)
library(tidyverse)
library(kableExtra)
library(flextable)
library(magrittr)
library(dplyr)
library(ggplot2)
library(hrbrthemes)
library(mishMashr)
library(patchwork)
library(ggridges)
theme_set(theme_minimal())
```

## Load the LGT table with all high-quality CDS candidates
```{r}
library(readxl)

# Read CDS level table to extract all unique LGTs later
LGTs<-read_excel("/Users/Janina/sciebo/MASTER/Masterarbeit/lgt/0_data/Tables/LGTs.CDSLevel.UniProt.Info.Reannotated.xlsx")
```

```{r}
colnames(LGTs)

# create grouping for protein type
LGTs$type<-"other"
LGTs$type[grep("Ankyrin|OTU|ankyrin|Tetratricopeptide repeat protein|TPR repeat-containing protein|Reverse transcriptase domain-containing protein|Phosphocholine_transferase_AnkX",LGTs$Protein.names)]<-"Ank"
LGTs$type[grep("Cyclopropane|EC 2.1.1.79",LGTs$Protein.names)]<-"CFA"
LGTs$type[grep("N-acetylmuramic",LGTs$Protein.names)]<-"MurNAc"
LGTs$type[grep("DUF1016|Lysozyme|lysozyme|Lyzozyme",LGTs$Protein.names)]<-"Lys"
LGTs$type[grep("methyltransferase",LGTs$Protein.names)]<-"MetA"

LGTs$type<-as.factor(LGTs$type)

LGTs$CDS.pids<-as.numeric(LGTs$CDS.pids)
LGTs$CDS.totalcounts<-as.numeric(LGTs$CDS.totalcounts)

# Filter out everything not expressed
expressed.LGTs<-LGTs %>%
  dplyr::filter(CDS.totalcounts > 100) 
```

Plot the percentage identity (CDS.pids) with the bacterial reference protein against expression (CDS.total.counts).
```{r}
# Plot percentage identity of all CDS based on their defined type
p1<-ggplot(LGTs, aes(x=CDS.pids,y=type, color=type)) + 
    geom_boxplot() +
    theme_minimal() +
   labs(x="% identity",
       y="Expression")
p1

# Plot % identity as a density plot
p1.5<-LGTs %>%
  mutate(type = fct_relevel(type, 
                             "other", "MurNAc", 
                             "MetA", "Lys","CFA", "Ank")) %>%
    ggplot(aes(x = CDS.pids, y = type)) +
    geom_density_ridges(aes(fill = type, rel_min_height = 0.001)) +
    theme(legend.position = "none") +
    labs(x="Identity with bacterial reference protein (%)")
p1.5

ggsave("/Users/Janina/Documents/MASTER/Masterarbeit/plots/IdentityPlot_Density.pdf", p1.5, width=15, height=10)
 
# With density gradient
p2 <- LGTs %>%
  mutate(type = fct_relevel(type, 
                             "other", "Unknown", "Fragmented", 
                             "TE-related", "Ribosomal protein", "MurNAc", 
                             "MetA", "Lys","CFA", "Ank")) %>%
  ggplot(aes(x = CDS.pids, y = type, fill = after_stat(x))) +
  geom_density_ridges_gradient(scale = 3, size = 0.3, rel_min_height = 0.01) +
  scale_fill_viridis_c(name = "Identity (%)", option = "A") +
  labs(x = "Identity with bacterial reference protein")
p2

ggsave("/Users/Janina/Documents/MASTER/Masterarbeit/plots/IdentityPlot_DensityGradient.pdf", p2, width=15, height=10)
```

Plot RNAseq expression for GAGA-0515 LGT
```{r}
# Read Excel table with normalized RNAseq expression 
Cobs_LGT<-read_excel("/Users/Janina/Documents/PhD/1_CompGenTEs/0_data/LGT_mapping/CARD-0001_LGT_counts_normalized_all.xlsx")

Cobs_LGT$life_stage<-as.factor(Cobs_LGT$life_stage)

Cobs_control<-Cobs_LGT %>%
  dplyr::filter(group=="control")

Cobs_treatment<-Cobs_LGT %>%
  dplyr::filter(group=="treatment")

Cobs_worker<-Cobs_LGT %>%
  dplyr::filter(group=="worker")

# Plot the different life stages (queen larvae, worker larvae, adult workers as a grouped boxplot)
# One box per treatment
p1 <- ggplot(Cobs_control, aes(x=life_stage, y=CPM_mapped)) + 
    geom_boxplot() +
    facet_wrap(~group) +
  geom_dotplot(binaxis= "y", stackdir="center", alpha=0.7, binwidth=0.8) +
  theme_classic()
p1

p2 <- ggplot(Cobs_treatment, aes(x=life_stage, y=CPM_mapped)) + 
    geom_boxplot() +
    facet_wrap(~group) +
  geom_dotplot(binaxis= "y", stackdir="center", alpha=0.9, binwidth=0.6) +
  theme_classic()
p2

p3 <- ggplot(Cobs_worker, aes(x=life_stage, y=CPM_mapped)) + 
    geom_boxplot() +
    facet_wrap(~group) +
  geom_dotplot(binaxis= "y", stackdir="center", alpha=0.9, binwidth=0.3) +
  theme_classic()
p3

combi<-p1+p2+p3
combi

ggsave("/Users/Janina/Documents/PhD/1_CompGenTEs/0_data/LGT_mapping/RNAseq_Cobs_LGT.pdf",combi, height = 7, width = 10)
```


# Plot bacterial donors 
```{r}
LGTs.loci<-read_excel("/Users/Janina/sciebo/HGT_Manuscript/Data/497_HQ_HGTs/Table_S2_HGTs_all_info.xlsx")

# create grouping for bacterial type, based on prokaryote origin but only one representative for each locus
LGTs.loci$bact.type<-"Other"
LGTs.loci$bact.type[grep("Wolbachia",LGTs.loci$prokaryote_origin)]<-"Wolbachia (Alphaproteobacteria)"
LGTs.loci$bact.type[grep("Enterobacterales",LGTs.loci$order_prokaryote_origin)]<-"Blochmannia-like (Gammaproteobacteria)"
LGTs.loci$bact.type[grep("Cardinium",LGTs.loci$prokaryote_origin)]<-"Cardinium (Sphingobacteriia)"
LGTs.loci$bact.type[grep("Spiroplasma|Mycoplasma",LGTs.loci$prokaryote_origin)]<-"Spiroplasma/Mycoplasma (Mollicutes)"

LGTs.loci$bact.type<-as.factor(LGTs.loci$bact.type)

# Plot the bacterial donors as a stacked barplot where each barplot represents the class and is filled with bacteria belonging to this class
pBac1 <- LGTs.loci %>%
  mutate(bact.type = fct_relevel(bact.type, 
                                 "Wolbachia (Alphaproteobacteria)","Blochmannia-like (Gammaproteobacteria)",
                                 "Spiroplasma/Mycoplasma (Mollicutes)","Cardinium (Sphingobacteriia)","Other")) %>%
  ggplot(aes(x=bact.type)) + 
    geom_bar(width=.6) +
  labs(y = "HGT count") +
    coord_flip() +
  theme(legend.position = "none")
pBac1

ggsave("/Users/Janina/Documents/MASTER/Masterarbeit/plots/HGT_loci_bac_donors.pdf", pBac1, width=12.5, height=10)

LGTs.loci %>% dplyr::count(bact.type)
```


